### PR TITLE
test out regridding to a sparse array

### PR DESCRIPTION
**Pull request by dcherian**
cc @bonnland

Tests out creating sparse+dask arrays for PFT variables. Looks like it works OK.

### CODE REVIEW

**Comment by wwieder** [comment]
Thanks for this contribution @dcherian! @danicalombardozzi I'm assuming this is faster than the code you were working on?

**Comment by dcherian** [comment]
> I'm assuming this is faster than the code you were working on?

It would be good to test it out! :)

**Comment by bonnland** [comment]
I'm working on it in my spare moment today or tomorrow!   Just figured out I need to clone deepak's xarray repo, not the pydata/xarray repo to get the updated code.

**Comment by danicalombardozzi** [comment]
I imagine it's much faster than my script. I think we'll want to test this out against the full data processing from my original script to ensure that the results are the same. For crops, we'll also need to consider the correct masking of crop area due to the merging of multiple crops in the code.

**Pull request merged**
