### PR TITLE
Interactive holoviews-based notebook with some FATES-relevant diagnostics

### PR DESCRIPTION
**Pull request by ckoven**
I made a notebook a while ago that uses the holoviews and panel libraries to make interactive visualizations.  The one thing is that these interactive plots don't render via the web -- you have to actually run the notebook to get them to work properly. So I hadn't submitted a PR while I wondered if there was a way to fix it.  But I am unlikely to figure that out,  and in the meantime it might be useful for others to use these as templates, so I thought I'd open a PR in the event that there is interest.

This PR contains two new files: (1) a notebook with some of the interactive visualizations, and (2) a netcdf file with some data that is used for the notebook. I tried to keep the file as small as possible (15MB) to minimize the overhead.

### CODE REVIEW

**Comment by katiedagon** [comment]
Thanks @ckoven! Tagging @negin513 since we just had a conversation about interactive visualization last week, and she might like to see these examples.

**Comment by ckoven** [comment]
great, thanks @katiedagon.  One thing I forgot to say in the intitial PR is that nbviewer does at least partially render the main holoviews figures, though not the actual updates to the adjacent figure panels that result from clicking on the main figure.  In both cases, the interactive part is that if you click on the map figure, the other panels update with timeseries of that gridcell.  holoviews is really great! let me know if anyone tries to run the notebook and runs into any problems.

nbviewer link at:
https://nbviewer.org/github/ckoven/ctsm_py/blob/fates_interactive/notebooks/fates_interactive_notebook.ipynb

**Comment by katiedagon** [comment]
@wwieder this PR came up in the PPE meeting today, do you want to merge this? Or anyone else who has write access to this repo - @samsrabin ?

**Comment by samsrabin** [comment]
Done! Thanks, both.

**Comment by wwieder** [comment]
Thanks Sam!

**Pull request merged**
